[metadata]
name = "libexample"
version = "1.2.3"
summary = "Exemplo de biblioteca"

[sources]
urls = [
  "https://example.org/libexample-1.2.3.tar.xz",
  "git+https://example.org/libexample.git@v1.2.3"
]
sha256 = ["sha256:AAAAAAAA..."]

[dependencies]
build = ["gcc@13.2.0", "pkg-config@0.29.2"]
runtime = ["zlib@1.3.0"]
optional = ["libopt@>=2.0"]

[phases]
# executadas na ordem
phases = ["fetch","extract","prepatch","patch","preconfigure","configure","build","check","install","postinstall"]

[hooks]
preconfigure = "scripts/preconf.sh"
postinstall = "scripts/postinstall.sh"

[build]
configure_flags = ["--prefix=@PREFIX@", "--enable-shared"]
env = { CFLAGS = "-O2 -g", CXXFLAGS = "-O2 -g" }
jobs = 8
